In [1]:
from tensorflow import keras

In [2]:
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

In [3]:
print(x_train.shape, x_test.shape)

(60000, 28, 28) (10000, 28, 28)


In [4]:
print(y_train.shape, y_test.shape)

(60000,) (10000,)


In [5]:
for i in range(3):
    print(y_train[i])

5
0
4


In [6]:
y_train = keras.utils.to_categorical(y_train,10)
y_test = keras.utils.to_categorical(y_test,10)

In [9]:
for i in range(3):
    print(y_train[i])

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [11]:
x_train = x_train.reshape([60000,28*28]) # 2차원으로 변경?
x_test = x_test.reshape([10000,28*28])

In [12]:
print(x_train.shape, x_test.shape)

(60000, 784) (10000, 784)


In [44]:
model4 = keras.Sequential()

In [45]:
model4.add(keras.layers.Dense(128, activation="sigmoid", input_shape=(28*28,))) #input 변수 28*28
model4.add(keras.layers.Dense(256, activation="sigmoid"))
model4.add(keras.layers.Dense(10, activation="sigmoid")) # output 개수 10개

In [46]:
optimizer = keras.optimizers.SGD(lr=0.1)

In [47]:
model4.compile(optimizer=optimizer, loss="categorical_crossentropy", metrics=["accuracy"])

In [48]:
model4.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_17 (Dense)             (None, 128)               100480    
_________________________________________________________________
dense_18 (Dense)             (None, 256)               33024     
_________________________________________________________________
dense_19 (Dense)             (None, 10)                2570      
Total params: 136,074
Trainable params: 136,074
Non-trainable params: 0
_________________________________________________________________


In [49]:
model4.fit(x_train, y_train, batch_size=32, epochs=10, validation_data=(x_test, y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================] - 9s 145us/sample - loss: 0.8217 - accuracy: 0.7549 - val_loss: 0.6390 - val_accuracy: 0.8101
Epoch 2/10
60000/60000 [==============================] - 8s 136us/sample - loss: 0.7032 - accuracy: 0.7731 - val_loss: 0.6354 - val_accuracy: 0.7918
Epoch 3/10
60000/60000 [==============================] - 8s 140us/sample - loss: 0.7300 - accuracy: 0.7586 - val_loss: 0.6464 - val_accuracy: 0.7912
Epoch 4/10
60000/60000 [==============================] - 9s 144us/sample - loss: 0.7093 - accuracy: 0.7664 - val_loss: 0.6664 - val_accuracy: 0.7704
Epoch 5/10
60000/60000 [==============================] - 8s 137us/sample - loss: 0.6757 - accuracy: 0.7770 - val_loss: 0.6331 - val_accuracy: 0.7966
Epoch 6/10
60000/60000 [==============================] - 8s 136us/sample - loss: 0.6628 - accuracy: 0.7828 - val_loss: 0.6525 - val_accuracy: 0.7904
Epoch 7/10
60000/60000 [==========================