In [1]:
from tensorflow import keras

In [2]:
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

In [3]:
print(x_train.shape, x_test.shape)

(60000, 28, 28) (10000, 28, 28)


In [4]:
print(y_train.shape, y_test.shape)

(60000,) (10000,)


In [5]:
for i in range(3):
    print(y_train[i])

5
0
4


In [6]:
y_train = keras.utils.to_categorical(y_train,10)
y_test = keras.utils.to_categorical(y_test,10)

In [7]:
for i in range(3):
    print(y_train[i])

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [8]:
x_train = x_train.reshape([60000,28*28]) # 2차원으로 변경?
x_test = x_test.reshape([10000,28*28])

In [9]:
print(x_train.shape, x_test.shape)

(60000, 784) (10000, 784)


In [12]:
model = keras.Sequential()

In [13]:
model.add(keras.layers.Dense(128, activation="relu", input_shape=(28*28,))) #input 변수 28*28
model.add(keras.layers.Dense(128, activation="relu"))
model.add(keras.layers.Dense(128, activation="relu"))
model.add(keras.layers.Dense(128, activation="relu"))
model.add(keras.layers.Dense(128, activation="relu"))
model.add(keras.layers.Dense(10, activation="softmax")) # output 개수 10개

In [14]:
optimizer = keras.optimizers.SGD(lr=0.01)
model.compile(optimizer=optimizer, loss="categorical_crossentropy", metrics=["accuracy"])

In [15]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 128)               100480    
_________________________________________________________________
dense_1 (Dense)              (None, 128)               16512     
_________________________________________________________________
dense_2 (Dense)              (None, 128)               16512     
_________________________________________________________________
dense_3 (Dense)              (None, 128)               16512     
_________________________________________________________________
dense_4 (Dense)              (None, 128)               16512     
_________________________________________________________________
dense_5 (Dense)              (None, 10)                1290      
Total params: 167,818
Trainable params: 167,818
Non-trainable params: 0
________________________________________________

In [17]:
model.fit(x_train, y_train, batch_size=64, epochs=20, validation_data=(x_test, y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/20
60000/60000 [==============================] - 8s 130us/sample - loss: nan - accuracy: 0.0988 - val_loss: nan - val_accuracy: 0.0980
Epoch 2/20
60000/60000 [==============================] - 7s 112us/sample - loss: nan - accuracy: 0.0987 - val_loss: nan - val_accuracy: 0.0980
Epoch 3/20
60000/60000 [==============================] - 7s 113us/sample - loss: nan - accuracy: 0.0987 - val_loss: nan - val_accuracy: 0.0980
Epoch 4/20
60000/60000 [==============================] - 7s 111us/sample - loss: nan - accuracy: 0.0987 - val_loss: nan - val_accuracy: 0.0980
Epoch 5/20
60000/60000 [==============================] - 7s 115us/sample - loss: nan - accuracy: 0.0987 - val_loss: nan - val_accuracy: 0.0980
Epoch 6/20
60000/60000 [==============================] - 7s 113us/sample - loss: nan - accuracy: 0.0987 - val_loss: nan - val_accuracy: 0.0980
Epoch 7/20
60000/60000 [==============================] - 7s 118us/sample - loss: nan 